on:
  push:
    branches: [ master ]
name: ðŸš€ DEPLOY WEBSITE
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš OBTENDO ORIGIN MASTER
      uses: actions/checkout@v2.3.2
    
    - name: ðŸ“‚ SINCRONIZANDO ARQUIVOS
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.lupustech.dev
        username: u815403761.aula
        password: ${{ secrets.ftp_password }}
