on:
  push:
   branches: [ master ]

name: ðŸš€ Deploy FTP ðŸš€
jobs: 
  web-deploy:
    name:  Deploy
    run-on: ubuntu-latest
    steps:
    - name: Obtendo Origin Master
    uses: actions/checkout@v2.3.2

    - name: Sincronizando Arquivos
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp://lupustech.dev
        username: u815403761.aula
        password: ${{ secrets.ftp_password }}


